package com.lostsidewalk.buffy.newsapi;

@SuppressWarnings("unused")
public enum NewsApiSources {

    ABC_NEWS("ABC News", "Your trusted source for breaking news, analysis, exclusive interviews, headlines, and videos at ABCNews.com.", "https://abcnews.go.com", "general", "us", "en"),
    ABC_NEWS_AU("ABC News (AU)", "Australia's most trusted source of local, national and world news. Comprehensive, independent, in-depth analysis, the latest business, sport, weather and more.", "http://www.abc.net.au/news", "general", "au", "en"),
    AFTENPOSTEN("Aftenposten", "Norges ledende nettavis med alltid oppdaterte nyheter innenfor innenriks, utenriks, sport og kultur.", "https://www.aftenposten.no", "general", "no", "no"),
    AL_JAZEERA_ENGLISH("Al Jazeera English", "News, analysis from the Middle East and worldwide, multimedia and interactives, opinions, documentaries, podcasts, long reads and broadcast schedule.", "http://www.aljazeera.com", "general", "us", "en"),
    ANSA_IT("ANSA.it", "Agenzia ANSA: ultime notizie, foto, video e approfondimenti su: cronaca, politica, economia, regioni, mondo, sport, calcio, cultura e tecnologia.", "http://www.ansa.it", "general", "it", "it"),
    ARGAAM("Argaam", "ارقام موقع متخصص في متابعة سوق الأسهم السعودي تداول - تاسي - مع تغطيه معمقة لشركات واسعار ومنتجات البتروكيماويات , تقارير مالية الاكتتابات الجديده ", "http://www.argaam.com", "business", "sa", "ar"),
    ARS_TECHNICA("Ars Technica", "The PC enthusiast's resource. Power users and the tools they love, without computing religion.", "http://arstechnica.com", "technology", "us", "en"),
    ARY_NEWS("Ary News", "ARY News is a Pakistani news channel committed to bring you up-to-the minute Pakistan news and featured stories from around Pakistan and all over the world.", "https://arynews.tv/ud/", "general", "pk", "ud"),
    ASSOCIATED_PRESS("Associated Press", "The AP delivers in-depth coverage on the international, politics, lifestyle, business, and entertainment news.", "https://apnews.com/", "general", "us", "en"),
    AUSTRALIAN_FINANCIAL_REVIEW("Australian Financial Review", "The Australian Financial Review reports the latest news from business, finance, investment and politics, updated in real time. It has a reputation for independent, award-winning journalism and is essential reading for the business and investor community.", "http://www.afr.com", "business", "au", "en"),
    AXIOS("Axios", "Axios are a new media company delivering vital, trustworthy news and analysis in the most efficient, illuminating and shareable ways possible.", "https://www.axios.com", "general", "us", "en"),
    BBC_NEWS("BBC News", "Use BBC News for up-to-the-minute news, breaking news, video, audio and feature stories. BBC News provides trusted World and UK news as well as local and regional perspectives. Also entertainment, business, science, technology and health news.", "http://www.bbc.co.uk/news", "general", "gb", "en"),
    BBC_SPORT("BBC Sport", "The home of BBC Sport online. Includes live sports coverage, breaking news, results, video, audio and analysis on Football, F1, Cricket, Rugby Union, Rugby League, Golf, Tennis and all the main world sports, plus major events such as the Olympic Games.", "http://www.bbc.co.uk/sport", "sports", "gb", "en"),
    BILD("Bild", "Die Seite 1 für aktuelle Nachrichten und Themen, Bilder und Videos aus den Bereichen News, Wirtschaft, Politik, Show, Sport, und Promis.", "http://www.bild.de", "general", "de", "de"),
    BLASTING_NEWS_BR("Blasting News (BR)", "Descubra a seção brasileira da Blasting News, a primeira revista feita pelo  público, com notícias globais e vídeos independentes. Junte-se a nós e torne- se um repórter.", "https://br.blastingnews.com", "general", "br", "pt"),
    BLEACHER_REPORT("Bleacher Report", "Sports journalists and bloggers covering NFL, MLB, NBA, NHL, MMA, college football and basketball, NASCAR, fantasy sports and more. News, photos, mock drafts, game scores, player profiles and more!", "http://www.bleacherreport.com", "sports", "us", "en"),
    BLOOMBERG("Bloomberg", "Bloomberg delivers business and markets news, data, analysis, and video to the world, featuring stories from Businessweek and Bloomberg News.", "http://www.bloomberg.com", "business", "us", "en"),
    BREITBART_NEWS("Breitbart News", "Syndicated news and opinion website providing continuously updated headlines to top news and analysis sources.", "http://www.breitbart.com", "general", "us", "en"),
    BUSINESS_INSIDER("Business Insider", "Business Insider is a fast-growing business site with deep financial, media, tech, and other industry verticals. Launched in 2007, the site is now the largest business news site on the web.", "http://www.businessinsider.com", "business", "us", "en"),
    BUSINESS_INSIDER_UK("Business Insider (UK)", "Business Insider is a fast-growing business site with deep financial, media, tech, and other industry verticals. Launched in 2007, the site is now the largest business news site on the web.", "http://uk.businessinsider.com", "business", "gb", "en"),
    BUZZFEED("Buzzfeed", "BuzzFeed is a cross-platform, global network for news and entertainment that generates seven billion views each month.", "https://www.buzzfeed.com", "entertainment", "us", "en"),
    CBC_NEWS("CBC News", "CBC News is the division of the Canadian Broadcasting Corporation responsible for the news gathering and production of news programs on the corporation's English-language operations, namely CBC Television, CBC Radio, CBC News Network, and CBC.ca.", "http://www.cbc.ca/news", "general", "ca", "en"),
    CBS_NEWS("CBS News", "CBS News: dedicated to providing the best in journalism under standards it pioneered at the dawn of radio and television and continue in the digital age.", "http://www.cbsnews.com", "general", "us", "en"),
    CNN("CNN", "View the latest news and breaking news today for U.S., world, weather, entertainment, politics and health at CNN", "http://us.cnn.com", "general", "us", "en"),
    CNN_SPANISH("CNN Spanish", "Lee las últimas noticias e información sobre Latinoamérica, Estados Unidos, mundo, entretenimiento, política, salud, tecnología y deportes en CNNEspañol.com.", "http://cnnespanol.cnn.com/", "general", "us", "es"),
    CRYPTO_COINS_NEWS("Crypto Coins News", "Providing breaking cryptocurrency news - focusing on Bitcoin, Ethereum, ICOs, blockchain technology, and smart contracts.", "https://www.ccn.com", "technology", "us", "en"),
    DER_TAGESSPIEGEL("Der Tagesspiegel", "Nachrichten, News und neueste Meldungen aus dem Inland und dem Ausland - aktuell präsentiert von tagesspiegel.de.", "http://www.tagesspiegel.de", "general", "de", "de"),
    DIE_ZEIT("Die Zeit", "Aktuelle Nachrichten, Kommentare, Analysen und Hintergrundberichte aus Politik, Wirtschaft, Gesellschaft, Wissen, Kultur und Sport lesen Sie auf ZEIT ONLINE.", "http://www.zeit.de/index", "business", "de", "de"),
    EL_MUNDO("El Mundo", "Noticias, actualidad, álbumes, debates, sociedad, servicios, entretenimiento y última hora en España y el mundo.", "http://www.elmundo.es", "general", "es", "es"),
    ENGADGET("Engadget", "Engadget is a web magazine with obsessive daily coverage of everything new in gadgets and consumer electronics.", "https://www.engadget.com", "technology", "us", "en"),
    ENTERTAINMENT_WEEKLY("Entertainment Weekly", "Online version of the print magazine includes entertainment news, interviews, reviews of music, film, TV and books, and a special area for magazine subscribers.", "http://www.ew.com", "entertainment", "us", "en"),
    ESPN("ESPN", "ESPN has up-to-the-minute sports news coverage, scores, highlights and commentary for NFL, MLB, NBA, College Football, NCAA Basketball and more.", "http://espn.go.com", "sports", "us", "en"),
    ESPN_CRIC_INFO("ESPN Cric Info", "ESPN Cricinfo provides the most comprehensive cricket coverage available including live ball-by-ball commentary, news, unparalleled statistics, quality editorial comment and analysis.", "http://www.espncricinfo.com/", "sports", "us", "en"),
    FINANCIAL_POST("Financial Post", "Find the latest happenings in the Canadian Financial Sector and stay up to date with changing trends in Business Markets. Read trading and investing advice from professionals.", "http://business.financialpost.com", "business", "ca", "en"),
    FOCUS("Focus", "Minutenaktuelle Nachrichten und Service-Informationen von Deutschlands modernem Nachrichtenmagazin.", "http://www.focus.de", "general", "de", "de"),
    FOOTBALL_ITALIA("Football Italia", "Italian football news, analysis, fixtures and results for the latest from Serie A, Serie B and the Azzurri.", "http://www.football-italia.net", "sports", "it", "en"),
    FORTUNE("Fortune", "Fortune 500 Daily and Breaking Business News", "http://fortune.com", "business", "us", "en"),
    FOURFOURTWO("FourFourTwo", "The latest football news, in-depth features, tactical and statistical analysis from FourFourTwo, the UK&#039;s favourite football monthly.", "http://www.fourfourtwo.com/news", "sports", "gb", "en"),
    FOX_NEWS("Fox News", "Breaking News, Latest News and Current News from FOXNews.com. Breaking news and video. Latest Current News: U.S., World, Entertainment, Health, Business, Technology, Politics, Sports.", "http://www.foxnews.com", "general", "us", "en"),
    FOX_SPORTS("Fox Sports", "Find live scores, player and team news, videos, rumors, stats, standings, schedules and fantasy games on FOX Sports.", "http://www.foxsports.com", "sports", "us", "en"),
    GLOBO("Globo", "Só na globo.com você encontra tudo sobre o conteúdo e marcas do Grupo Globo. O melhor acervo de vídeos online sobre entretenimento, esportes e jornalismo do Brasil.", "http://www.globo.com/", "general", "br", "pt"),
    GOOGLE_NEWS("Google News", "Comprehensive, up-to-date news coverage, aggregated from sources all over the world by Google News.", "https://news.google.com", "general", "us", "en"),
    GOOGLE_NEWS_ARGENTINIA("Google News (Argentina)", "Completa cobertura actualizada de noticias agregadas a partir de fuentes de todo el mundo por Google Noticias.", "https://news.google.com", "general", "ar", "es"),
    GOOGLE_NEWS_AUSTRALIA("Google News (Australia)", "Comprehensive, up-to-date Australia news coverage, aggregated from sources all over the world by Google News.", "https://news.google.com", "general", "au", "en"),
    GOOGLE_NEWS_BRASIL("Google News (Brasil)", "Cobertura jornalística abrangente e atualizada, agregada de fontes do mundo inteiro pelo Google Notícias.", "https://news.google.com", "general", "br", "pt"),
    GOOGLE_NEWS_CANADA("Google News (Canada)", "Comprehensive, up-to-date Canada news coverage, aggregated from sources all over the world by Google News.", "https://news.google.com", "general", "ca", "en"),
    GOOGLE_NEWS_FRANCE("Google News (France)", "Informations complètes et à jour, compilées par Google Actualités à partir de sources d&#39;actualités du monde entier.", "https://news.google.com", "general", "fr", "fr"),
    GOOGLE_NEWS_INDIA("Google News (India)", "Comprehensive, up-to-date India news coverage, aggregated from sources all over the world by Google News.", "https://news.google.com", "general", "in", "en"),
    GOOGLE_NEWS_ISRAEL("Google News (Israel)", "כיסוי מקיף ועדכני של חדשות שהצטברו ממקורות בכל העולם על ידי &#39;חדשות Google&#39;.", "https://news.google.com", "general", "is", "he"),
    GOOGLE_NEWS_ITALY("Google News (Italy)", "Copertura giornalistica completa e aggiornata ottenuta combinando fonti di notizie in tutto il mondo attraverso Google News.", "https://news.google.com", "general", "it", "it"),
    GOOGLE_NEWS_RUSSIA("Google News (Russia)", "Исчерпывающая и актуальная информация, собранная службой &quot;Новости Google&quot; со всего света.", "https://news.google.com", "general", "ru", "ru"),
    GOOGLE_NEWS_SAUDI_ARABIA("Google News (Saudi Arabia)", "تغطية شاملة ومتجددة للأخبار، تم جمعها من مصادر أخبار من جميع أنحاء العالم بواسطة أخبار Google.", "https://news.google.com", "general", "sa", "ar"),
    GOOGLE_NEWS_UK("Google News (UK)", "Comprehensive, up-to-date UK news coverage, aggregated from sources all over the world by Google News.", "https://news.google.com", "general", "gb", "en"),
    GOTEBORGS_POSTEN("Göteborgs-Posten", "Göteborgs-Posten, abbreviated GP, is a major Swedish language daily newspaper published in Gothenburg, Sweden.", "http://www.gp.se", "general", "se", "sv"),
    GRUENDERSZENE("Gruenderszene", "Online-Magazin für Startups und die digitale Wirtschaft. News und Hintergründe zu Investment, VC und Gründungen.", "http://www.gruenderszene.de", "technology", "de", "de"),
    HACKER_NEWS("Hacker News", "Hacker News is a social news website focusing on computer science and entrepreneurship. It is run by Paul Graham's investment fund and startup incubator, Y Combinator. In general, content that can be submitted is defined as \"anything that gratifies one's intellectual curiosity\".", "https://news.ycombinator.com", "technology", "us", "en"),
    HANDELSBLATT("Handelsblatt", "Auf Handelsblatt lesen sie Nachrichten über Unternehmen, Finanzen, Politik und Technik. Verwalten Sie Ihre Finanzanlagen mit Hilfe unserer Börsenkurse.", "http://www.handelsblatt.com", "business", "de", "de"),
    IGN("IGN", "IGN is your site for Xbox One, PS4, PC, Wii-U, Xbox 360, PS3, Wii, 3DS, PS Vita and iPhone games with expert reviews, news, previews, trailers, cheat codes, wiki guides and walkthroughs.", "http://www.ign.com", "entertainment", "us", "en"),
    IL_SOLE_24_ORE("Il Sole 24 Ore", "Notizie di economia, cronaca italiana ed estera, quotazioni borsa in tempo reale e di finanza, norme e tributi, fondi e obbligazioni, mutui, prestiti e lavoro a cura de Il Sole 24 Ore.", "https://www.ilsole24ore.com", "business", "it", "it"),
    INDEPENDENT("Independent", "National morning quality (tabloid) includes free online access to news and supplements. Insight by Robert Fisk and various other columnists.", "http://www.independent.co.uk", "general", "gb", "en"),
    INFOBAE("Infobae", "Noticias de Argentina y del mundo en tiempo real. Información, videos y fotos sobre los hechos más relevantes y sus protagonistas. Léelo antes en infobae.", "http://www.infobae.com/?noredirect", "general", "ar", "es"),
    INFOMONEY("InfoMoney", "No InfoMoney você encontra tudo o que precisa sobre dinheiro. Ações, investimentos, bolsas de valores e muito mais. Aqui você encontra informação que vale dinheiro!", "https://www.infomoney.com.br", "business", "br", "pt"),
    LA_GACETA("La Gaceta", "El diario de Tucumán, noticias 24 horas online - San Miguel de Tucumán - Argentina - Ultimo momento - Ultimas noticias.", "http://www.lagaceta.com.ar", "general", "ar", "es"),
    LA_NACION("La Nacion", "Información confiable en Internet. Noticias de Argentina y del mundo - ¡Informate ya!", "http://www.lanacion.com.ar", "general", "ar", "es"),
    LA_REPUBBLICA("La Repubblica", "Breaking News, Latest News and Current News from FOXNews.com. Breaking news and video. Latest Current News: U.S., World, Entertainment, Health, Business, Technology, Politics, Sports.", "http://www.repubblica.it", "general", "it", "it"),
    LENTA("Lenta", "Новости, статьи, фотографии, видео. Семь дней в неделю, 24 часа в сутки.", "https://lenta.ru", "general", "ru", "ru"),
    LEQUIPE("L'equipe", "Le sport en direct sur L'EQUIPE.fr. Les informations, résultats et classements de tous les sports. Directs commentés, images et vidéos à regarder et à partager !", "https://www.lequipe.fr", "sports", "fr", "fr"),
    LES_ECHOS("Les Echos", "Toute l'actualité économique, financière et boursière française et internationale sur Les Echos.fr", "https://www.lesechos.fr", "business", "fr", "fr"),
    LE_MONDE("Le Monde", "Les articles du journal et toute l'actualit&eacute; en continu : International, France, Soci&eacute;t&eacute;, Economie, Culture, Environnement, Blogs ...", "http://www.lemonde.fr", "general", "fr", "fr"),
    LIBERATION("Libération", "Toute l'actualité en direct - photos et vidéos avec Libération", "http://www.liberation.fr", "general", "fr", "fr"),
    MARCA("Marca", "La mejor información deportiva en castellano actualizada minuto a minuto en noticias, vídeos, fotos, retransmisiones y resultados en directo.", "http://www.marca.com", "sports", "es", "es"),
    MASHABLE("Mashable", "Mashable is a global, multi-platform media and entertainment company.", "https://mashable.com", "entertainment", "us", "en"),
    MEDICAL_NEWS_TODAy("Medical News Today", "Medical news and health news headlines posted throughout the day, every day.", "http://www.medicalnewstoday.com", "health", "us", "en"),
    MSNBC("MSNBC", "Breaking news and in-depth analysis of the headlines, as well as commentary and informed perspectives from The Rachel Maddow Show, Morning Joe & more.", "http://www.msnbc.com", "general", "us", "en"),
    MTV_NEWS("MTV News", "The ultimate news source for music, celebrity, entertainment, movies, and current events on the web. It's pop culture on steroids.", "http://www.mtv.com/news", "entertainment", "us", "en"),
    MTV_NEWS_UK("MTV News (UK)", "All the latest celebrity news, gossip, exclusive interviews and pictures from the world of music and entertainment.", "http://www.mtv.co.uk/news", "entertainment", "gb", "en"),
    NATIONAL_GEOGRAPHIC("National Geographic", "Reporting our world daily: original nature and science news from National Geographic.", "http://news.nationalgeographic.com", "science", "us", "en"),
    NATIONAL_REVIEW("National Review", "National Review: Conservative News, Opinion, Politics, Policy, & Current Events.", "https://www.nationalreview.com/", "general", "us", "en"),
    NBC_NEWS("NBC News", "Breaking news, videos, and the latest top stories in world news, business, politics, health and pop culture.", "http://www.nbcnews.com", "general", "us", "en"),
    NEWS24("News24", "South Africa's premier news source, provides breaking news on national, world, Africa, sport, entertainment, technology and more.", "http://www.news24.com", "general", "za", "en"),
    NEWSWEEK("Newsweek", "Newsweek provides in-depth analysis, news and opinion about international issues, technology, business, culture and politics.", "https://www.newsweek.com", "general", "us", "en"),
    NEWS_COM_AU("News.com.au", "We say what people are thinking and cover the issues that get people talking balancing Australian and global moments — from politics to pop culture.", "http://www.news.com.au", "general", "au", "en"),
    NEW_SCIENTIST("New Scientist", "Breaking science and technology news from around the world. Exclusive stories and expert analysis on space, technology, health, physics, life and Earth.", "https://www.newscientist.com/section/news", "science", "us", "en"),
    NEW_YORK_MAGAZINE("New York Magazine", "NYMAG and New York magazine cover the new, the undiscovered, the next in politics, culture, food, fashion, and behavior nationally, through a New York lens.", "http://nymag.com", "general", "us", "en"),
    NEXT_BIG_FUTURE("Next Big Future", "Coverage of science and technology that have the potential for disruption, and analysis of plans, policies, and technology that enable radical improvement.", "https://www.nextbigfuture.com", "science", "us", "en"),
    NFL_NEWS("NFL News", "The official source for NFL news, schedules, stats, scores and more.", "http://www.nfl.com/news", "sports", "us", "en"),
    NHL_NEWS("NHL News", "The most up-to-date breaking hockey news from the official source including interviews, rumors, statistics and schedules.", "https://www.nhl.com/news", "sports", "us", "en"),
    NRK("NRK", "NRK er Norges største tilbud på nett: nyheter fra Norge og verden, lokalnyheter, radio- og tv-program, podcast, vær, helse-, kultur-, underholdning-, humor- og debattstoff.", "https://www.nrk.no", "general", "no", "no"),
    POLITICO("Politico", "Political news about Congress, the White House, campaigns, lobbyists and issues.", "https://www.politico.com", "general", "us", "en"),
    POLYGON("Polygon", "Polygon is a gaming website in partnership with Vox Media. Our culture focused site covers games, their creators, the fans, trending stories and entertainment news.", "http://www.polygon.com", "entertainment", "us", "en"),
    RBC("RBC", "Главные новости политики, экономики и бизнеса, комментарии аналитиков, финансовые данные с российских и мировых биржевых систем на сайте rbc.ru.", "https://www.rbc.ru", "general", "ru", "ru"),
    RECODE("Recode", "Get the latest independent tech news, reviews and analysis from Recode with the most informed and respected journalists in technology and media.", "http://www.recode.net", "technology", "us", "en"),
    REDDIT_R_ALL("Reddit /r/all", "Reddit is an entertainment, social news networking service, and news website. Reddit's registered community members can submit content, such as text posts or direct links.", "https://www.reddit.com/r/all", "general", "us", "en"),
    REUTERS("Reuters", "Reuters.com brings you the latest news from around the world, covering breaking news in business, politics, entertainment, technology, video and pictures.", "http://www.reuters.com", "general", "us", "en"),
    RT("RT", "Актуальная картина дня на RT: круглосуточное ежедневное обновление новостей политики, бизнеса, финансов, спорта, науки, культуры. Онлайн-репортажи с места событий. Комментарии экспертов, актуальные интервью, фото и видео репортажи.", "https://russian.rt.com", "general", "ru", "ru"),
    RTE("RTE", "Get all of the latest breaking local and international news stories as they happen, with up to the minute updates and analysis, from Ireland's National Broadcaster.", "https://www.rte.ie/news", "general", "ie", "en"),
    RTL_NIEUWS("RTL Nieuws", "Volg het nieuws terwijl het gebeurt. RTL Nieuws informeert haar lezers op een onafhankelijke, boeiende en toegankelijke wijze over belangrijke ontwikkelingen in eigen land en de rest van de wereld.", "https://www.rtlnieuws.nl/", "general", "nl", "nl"),
    SABQ("SABQ", "صحيفة الكترونية سعودية هدفها السبق في نقل الحدث بمهنية ومصداقية خدمة للوطن والمواطن.", "https://sabq.org", "general", "sa", "ar"),
    SPIEGEL_ONLINE("Spiegel Online", "Deutschlands führende Nachrichtenseite. Alles Wichtige aus Politik, Wirtschaft, Sport, Kultur, Wissenschaft, Technik und mehr.", "http://www.spiegel.de", "general", "de", "de"),
    SVENSKA_DAGBLADET("Svenska Dagbladet", "Sveriges ledande mediesajt - SvD.se. Svenska Dagbladets nyhetssajt låter läsarna ta plats och fördjupar nyheterna.", "https://www.svd.se", "general", "se", "sv"),
    T3N("T3n", "Das Online-Magazin bietet Artikel zu den Themen E-Business, Social Media, Startups und Webdesign.", "https://t3n.de", "technology", "de", "de"),
    TALKSPORT("TalkSport", "Tune in to the world's biggest sports radio station - Live Premier League football coverage, breaking sports news, transfer rumours &amp; exclusive interviews.", "http://talksport.com", "sports", "gb", "en"),
    TECHCRUNCH("TechCrunch", "TechCrunch is a leading technology media property, dedicated to obsessively profiling startups, reviewing new Internet products, and breaking tech news.", "https://techcrunch.com", "technology", "us", "en"),
    TECHCRUNCH_CN("TechCrunch (CN)", "TechCrunch is a leading technology media property, dedicated to obsessively profiling startups, reviewing new Internet products, and breaking tech news.", "https://techcrunch.cn", "technology", "zh", "zh"),
    TECHRADAR("TechRadar", "The latest technology news and reviews, covering computing, home entertainment systems, gadgets and more.", "http://www.techradar.com", "technology", "us", "en"),
    THE_AMERICAN_CONSERVATIVE("The American Conservative", "Realism and reform. A new voice for a new generation of conservatives.", "http://www.theamericanconservative.com/", "general", "us", "en"),
    THE_GLOBE_AND_MAIL("The Globe And Mail", "The Globe and Mail offers the most authoritative news in Canada, featuring national and international news.", "https://www.theglobeandmail.com", "general", "ca", "en"),
    THE_HILL("The Hill", "The Hill is a top US political website, read by the White House and more lawmakers than any other site -- vital for policy, politics and election campaigns.", "http://thehill.com", "general", "us", "en"),
    THE_HINDU("The Hindu", "The Hindu. latest news, analysis, comment, in-depth coverage of politics, business, sport, environment, cinema and arts from India's national newspaper.", "http://www.thehindu.com", "general", "in", "en"),
    THE_HUFFINGTON_POST("The Huffington Post", "The Huffington Post is a politically liberal American online news aggregator and blog that has both localized and international editions founded by Arianna Huffington, Kenneth Lerer, Andrew Breitbart, and Jonah Peretti, featuring columnists.", "http://www.huffingtonpost.com", "general", "us", "en"),
    THE_IRISH_TIMES("The Irish Times", "The Irish Times online. Latest news including sport, analysis, business, weather and more from the definitive brand of quality news in Ireland.", "https://www.irishtimes.com", "general", "ie", "en"),
    THE_JERUSALEM_POST("The Jerusalem Post", "The Jerusalem Post is the leading online newspaper for English speaking Jewry since 1932, bringing news and updates from the Middle East and all over the Jewish world.", "https://www.jpost.com/", "general", "is", "en"),
    THE_LAD_BIBLE("The Lad Bible", "The LAD Bible is one of the largest community for guys aged 16-30 in the world. Send us your funniest pictures and videos!", "https://www.theladbible.com", "entertainment", "gb", "en"),
    THE_NEXT_WEB("The Next Web", "The Next Web is one of the world’s largest online publications that delivers an international perspective on the latest news about Internet technology, business and culture.", "http://thenextweb.com", "technology", "us", "en"),
    THE_SPORT_BIBLE("The Sport Bible", "TheSPORTbible is one of the largest communities for sports fans across the world. Send us your sporting pictures and videos!", "https://www.thesportbible.com", "sports", "gb", "en"),
    THE_TIMES_OF_INDIA("The Times of India", "Times of India brings the Latest News and Top Breaking headlines on Politics and Current Affairs in India and around the World, Sports, Business, Bollywood News and Entertainment, Science, Technology, Health and Fitness news, Cricket and opinions from leading columnists.", "http://timesofindia.indiatimes.com", "general", "in", "en"),
    THE_VERGE("The Verge", "The Verge covers the intersection of technology, science, art, and culture.", "http://www.theverge.com", "technology", "us", "en"),
    THE_WALL_STREET_JOURNAL("The Wall Street Journal", "WSJ online coverage of breaking news and current headlines from the US and around the world. Top stories, photos, videos, detailed analysis and in-depth reporting.", "http://www.wsj.com", "business", "us", "en"),
    THE_WASHINGTON_POST("The Washington Post", "Breaking news and analysis on politics, business, world national news, entertainment more. In-depth DC, Virginia, Maryland news coverage including traffic, weather, crime, education, restaurant reviews and more.", "https://www.washingtonpost.com", "general", "us", "en"),
    THE_WASHINGTON_TIMES("The Washington Times", "The Washington Times delivers breaking news and commentary on the issues that affect the future of our nation.", "https://www.washingtontimes.com/", "general", "us", "en"),
    TIME("Time", "Breaking news and analysis from TIME.com. Politics, world news, photos, video, tech reviews, health, science and entertainment news.", "http://time.com", "general", "us", "en"),
    USA_TODAY("USA Today", "Get the latest national, international, and political news at USATODAY.com.", "http://www.usatoday.com/news", "general", "us", "en"),
    VICE_NEWS("Vice News", "Vice News is Vice Media, Inc.'s current affairs channel, producing daily documentary essays and video through its website and YouTube channel. It promotes itself on its coverage of \"under - reported stories\".", "https://news.vice.com", "general", "us", "en"),
    WIRED("Wired", "Wired is a monthly American magazine, published in print and online editions, that focuses on how emerging technologies affect culture, the economy, and politics.", "https://www.wired.com", "technology", "us", "en"),
    WIRED_DE("Wired.de", "Wired reports on how emerging technologies affect culture, the economy and politics.", "https://www.wired.de", "technology", "de", "de"),
    WIRTSCHAFTS_WOCHE("Wirtschafts Woche", "Das Online-Portal des führenden Wirtschaftsmagazins in Deutschland. Das Entscheidende zu Unternehmen, Finanzen, Erfolg und Technik.", "http://www.wiwo.de", "business", "de", "de"),
    XINHUA_NET("Xinhua Net", "中国主要重点新闻网站,依托新华社遍布全球的采编网络,记者遍布世界100多个国家和地区,地方频道分布全国31个省市自治区,每天24小时同时使用6种语言滚动发稿,权威、准确、及时播发国内外重要新闻和重大突发事件,受众覆盖200多个国家和地区,发展论坛是全球知名的中文论坛。", "http://xinhuanet.com/", "general", "zh", "zh"),
    YNET("Ynet", "ynet דף הבית: אתר החדשות המוביל בישראל מבית ידיעות אחרונות. סיקור מלא של חדשות מישראל והעולם, ספורט, כלכלה, תרבות, אוכל, מדע וטבע, כל מה שקורה וכל מה שמעניין ב ynet.", "http://www.ynet.co.il", "general", "is", "he");

    public final String name;
    public final String description;
    public final String url;
    public final String category;
    public final String country;
    public final String language;

    NewsApiSources(String name, String description, String url, String category, String country, String language) {
        this.name = name;
        this.description = description;
        this.url = url;
        this.category = category;
        this.country = country;
        this.language = language;
    }
}
